server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
    #注册进consul
  cloud:
    cosnul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}