server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从服务注册中心动态创建路由的功能，利用微服务名进行路由。
      routes:
       - id: payment_route              #路由id，没有特殊意义
         #uri: http://localhost:8001      #匹配后提供服务的路径
         uri: lb://cloud-payment-service  #匹配后提供路由的地址
         predicates:
          - Path=/payment/get/**          #断言，路径相匹配的进行路由

       - id: payment_route2
#         uri: http://localhost:8001
         uri: lb://cloud-payment-service   #匹配后提供路由的地址
         predicates:        #当一下所有条件都为true后，才能成功访问
          - Path=/payment/lb/**     #断言，路径相匹配的进行路由
          - After=2022-10-24T16:02:52.469+08:00[Asia/Shanghai]    #当时间是写入时间后时，才能服务才能调用成功
          #- Cookie=name,zzxx      #请求中带有cookie



eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka