server:
  port: 80

spring:
  application:
    name: consumer-feign-hystrix-order

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true   #fegin开启hystrix
